export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INVENTORY_EXHAUSTED: "INVENTORY_EXHAUSTED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  ORDER_INVALID_STATE: "ORDER_INVALID_STATE",
  INTERNAL_ERROR: "INTERNAL_ERROR",
};
